version: 2.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run:
          name: Change git protocol
          command: git config --global url."https://".insteadOf git://
      - run:
          name: "Install Dependencies"
          command: yarn install
      - run:
          name: "Build Packages"
          command: yarn build
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
  lint:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.20
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Lint Packages"
          command: yarn lint
      - run:
          name: "Prettier Check"
          command: yarn prettier:ci
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.20
      - image: trufflesuite/ganache-cli:v6.5.1
        command: ganache-cli -i 1234 -p 8545 -e 10000000 -l 6721975
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Test Packages"
          command: yarn test
  coverage:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.20
      - image: trufflesuite/ganache-cli:v6.5.1
        command: ganache-cli -i 1234 -p 8545 -e 10000000 -l 6721975
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Cover Packages"
          command: yarn coverage
      - run:
          name: "Merge Results and Upload to Coveralls"
          command: 'yarn lcov-result-merger "packages/**/coverage/lcov.info"| yarn coveralls'
workflows:
  version: 2
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - lint
            - test
